### ISSUE TITLE
Make available on Github pages!

### ISSUE THREAD

**Issue by marcoscaceres** [cwilso/WebMIDIAPIShim#8]
It would be great if you could make this available on GH pages... having to clone it, etc. is a slight pain.

**Comment by cwilso** [comment]
An excellent idea!

http://cwilso.github.com/WebMIDIAPIShim/

**Comment by notator** [comment]
When I hit the button on the above link, I get the "Starting up MIDI..." message but an exception is thrown at WebMIDIAPI.js line 51:  the performance.now() method does not exist. I think it would work if you could fall back on performance.webkitNow(). Elsewhere too?
I'm on Windows Vista Ultimate 64bit, Browser: Chrome Version 23.0.1271.97 m

**Comment by cwilso** [comment]
Refresh, should be fixed now.

**Comment by notator** [comment]
```
Am 12.12.2012 22:48, schrieb Chris
  Wilson:

  Refresh, should be fixed now.

    —
    Reply to this email directly or view
      it on GitHub. 

I've been doing "Hard reload"s sporadically for the past 15 minutes.
The code hasn't changed...
best,
j-- 
```

www.james-ingram-act-two.de

**Comment by cwilso** [comment]
Whoops!  Sorry, only updated the master repo.  Try again now.

**Comment by notator** [comment]
I can see where you changed the code (line 7) but I still get an exception (now at line 54).
Simple windows.performance.webkitNow() works for me.

Talk to you again tomorrow. And so to bed. :-)
j

**Comment by cwilso** [comment]
Grr.  Try one more time.

**Comment by notator** [comment]
Its now working. Thanks!

**Comment by notator** [comment]
I've just tried clicking the button again, and now get an exception at line 64 of (program):
"Uncaught TypeError: Object #<Navigator> has no method 'getMIDIAccess'".

Windows Vista Ultimate 64bit, Browser: Chrome Version 23.0.1271.97 m

**Comment by cwilso** [comment]
Yup - the spec changed.  It's now called "requestMIDIAccess".

I just polyfilled the old name too, though, so it should work again now.

**Comment by notator** [comment]
Great, thanks. Its working again.
